export type SubscriberEventType = 'PROBABILITY_REACHED_70' | 'RESET_ANNOUNCED';

export type OperationalEventType =
  | 'RESET_COMPLETED'
  | 'SOURCE_DEGRADED'
  | 'SOURCE_RECOVERED'
  | 'SOURCE_UNAVAILABLE'
  | 'PARSER_FAILURE'
  | 'CYCLE_CREATED'
  | 'BOOTSTRAP_COMPLETE'
  | 'EVENT_CANDIDATES_SUPPRESSED'
  | 'SUBSCRIPTION_CONFIRMED'
  | 'SUBSCRIPTION_MANAGEMENT_LINK_REQUESTED'
  | 'DELIVERY_PREPARED'
  | 'DELIVERY_CLAIMED'
  | 'DELIVERY_SENT_TO_PROVIDER'
  | 'DELIVERY_RETRY_SCHEDULED'
  | 'DELIVERY_PERMANENTLY_FAILED'
  | 'DELIVERY_CANCELLED'
  | 'DELIVERY_STALE_CLAIM_RECOVERED';

export interface ProbabilityReached70Payload {
  threshold: 70;
  previousProbability: number;
  currentProbability: number;
}
